name: Build Project
on:
  push
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Dependencies
        run: npm install
      - name: Run Tests
        run: nx test  react-cookie-service
      - name: Build project
        run: npm run  build  react-cookie-service
