name: Publish React Cookie Service to NPM
on:
  push:
    ### Publish on new tag release
    tags:
      - v*
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Build project
        run: pnpm build react-cookie-service
      - name: Run Tests
        run: pnpm test react-cookie-service
      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: libs/react-cookie-service/package.json
          access: public
