name: Publish JS Cookie Service to NPM
on:
  push:
    ### Publish on new tag release
    tags:
      - v*
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm install --force
      - name: Build project
        run: npm run build js-cookie-service
      - name: Run Tests
        run: npm test js-cookie-service
      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: libs/js-cookie-service/package.json
          access: public
